config/routes.rb
ShamanimeCom::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout" }

  namespace 'admin' do
    resources :users, :except => :show
    resources :posts, :except => :show
    root :to => 'posts#index'
    
    match '*a', :to => 'posts#index'
  end
  
  post "/contact", :controller => :contact, :action => :contact
  get "/contact", :controller => :pages, :action => :contact
  resources :posts, :only => [:index, :show]
  root :to => 'posts#index'
  
  match '*a', :to => 'posts#index'
end

app/models/contact.rb
# encoding: utf-8
class Contact
  include ActiveModel::Validations
  
  validates_presence_of :name, :email, :message
  # to deal with form, you must have an id attribute
  attr_accessor :id,:name, :email, :message
  
  validates :email, :format => { :with => /^([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})$/i }, :allow_blank => :true

  def initialize(attributes = {})
    attributes.each do |key, value|
      self.send("#{key}=", value)
    end
    @attributes = attributes
  end

  def read_attribute_for_validation(key)
    @attributes[key]
  end

  def to_key
  end

  def save
    if self.valid?
      Site.contact(@attributes).deliver
      return true
    end
    return false
  end
end

app/models/post.rb
require 'rdiscount'
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  
  paginates_per 7
  
  belongs_to :user
  
  scope :published, where(draft: "false")
  field :title, :type => String
  field :body, :type => String
  field :draft, :type => Boolean, :default => false
  field :published_at, :type => Date, :default => Time.now
  
  validates_presence_of :title, :body, :published_at, :user
  
  slug :title, :permanent => true
  
  def to_param
    slug
  end
  
  def markdown_body
    markdown_body = RDiscount.new(body).to_html
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable
  
  has_many :posts

  field :name
  field :username, :type => String
  field :email, :type => String
  validates_presence_of :name, :username
  validates_uniqueness_of :username, :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :username
  
  def last_post
    post = posts.published.desc(:created_at).first
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController <  Admin::BaseController
  respond_to :html, :json
  before_filter :get_users, :except => [:index, :destroy]
  
  def index
    @title = "Post listing"
    @posts = Post.all.desc(:created_at)
  end

  def new
    @title = "New post"
    @post = Post.new
  end

  def edit
    @title = "Edit post"
    @post = Post.find_by_slug(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    respond_with @post do |format|
      if @post.save
        format.html { redirect_to admin_posts_url, :flash => { success: 'Post was successfully created.' } }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @post = Post.find_by_slug(params[:id])
    respond_with @post do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to admin_posts_url, :flash => { success: 'Post was successfully updated.' } }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @post = Post.find_by_slug(params[:id])
    @post.destroy
    respond_with @post do |format|
      format.html { redirect_to admin_posts_url, :flash => { success: 'Post was successfully destroyed.' } }
    end
  end
  
  private
  def get_users
    @users = User.all
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController <  Admin::BaseController
  respond_to :html, :json
  
  def index
    @title = "User listing"
    @users = User.all
  end

  def new
    @title = "New user"
    @user = User.new
  end

  def edit
    @title = "Edit user"
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    respond_with @user do |format|
      if @user.save
        format.html { redirect_to admin_users_url, :flash => { success: 'User was successfully created.' } }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    respond_with @user do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_url, :flash => { success: 'User was successfully updated.' } }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @user do |format|
      format.html { redirect_to admin_users_url, :flash => { success: 'User was successfully destroyed.' } }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :layout_by_resource
  before_filter :load_recent_posts

  def layout_by_resource
    if devise_controller?
      "admin"
    else
      "application"
    end
  end
  
  def load_recent_posts
    @recent_posts = Post.published.desc(:created_at).limit(10)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
    @contact = Contact.new(params[:contact])
    respond_to do |format|
      if @contact.save
        format.html { redirect_to contato_path, :flash => { :success => 'Message sent successfully!' } }
        format.js { render :partial => "success" }
      else
        format.html { redirect_to contato_path, :flash => { :error => 'There was a problem sending your message!' } }
        format.js { render :partial => "error" }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
    @title = "Contact"
    @contact = Contact.new(:id =>1)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.published.desc(:created_at).page params[:page]
  end
  
  def show
    if @post = Post.find_by_slug(params[:id])
      @title = @post.title
    else
      redirect_to root_path, :notice => 'The post you were looking for couldn\'t be found.'
    end
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/post_helper.rb
module Admin::PostHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = t ('head.title')
    if @title.nil?
      base_title
    else
      "#{base_title} - #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.haml
= form_for [:admin, @post] do |f|
  -if @post.errors.any?
    .alert-message.block-message.error
      %p
        %strong= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %p
        %ol
          - @post.errors.full_messages.each do |msg|
            %li= msg
  %fieldset
    %legend= @title
    .clearfix
      = f.label :title
      .input= f.text_field :title, :class => "xxlarge"
    .clearfix
      = f.label :body
      .input= f.text_area :body, :rows => 15, :class => "xxlarge"
    .clearfix
      = f.label :author
      .input= f.collection_select(:user, @users, :id, :username, { :selected => (@post.user.id unless f.object.new_record?) }, { :class => "xlarge" } )
    .clearfix
      = f.label :published_at
      .input= f.text_field :published_at, :class => "small"
    .clearfix
      = f.label :draft
      .input
        %ul.inputs-list
          %li
            .label
              = f.check_box :draft
              %span Save this post as a draft.
    .actions
      = f.submit :class => 'btn primary'
      = link_to 'Cancel', admin_posts_path, :class => 'btn'

app/views/admin/posts/edit.html.haml
= render 'form'

app/views/admin/posts/index.html.haml
%h1= @title
%table
  %thead
    %tr
      %th Created at
      %th Author
      %th Title
      %th Published?
      %th Actions
  %tbody
    - for post in @posts
      %tr
        %td= l post.created_at, :format => :long
        %td= post.user.name
        %td= link_to post.title, post_path(post), :target => "_blank"
        %td
          - if post.draft?
            Draft
          - else
            = l post.published_at
        %td
          = link_to "Edit", edit_admin_post_path(post)
          |
          = link_to "Delete", admin_post_path(post), :confirm => 'Are you sure?', :method => :delete, :title => "Delete post"
= link_to "New post", new_admin_post_url, :class => "btn primary"

app/views/admin/posts/new.html.haml
= render 'form'

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
  -if @user.errors.any?
    .alert-message.block-message.error
      %p
        %strong= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %p
        %ol
          - @user.errors.full_messages.each do |msg|
            %li= msg
  %fieldset
    %legend= @title
    .clearfix
      = f.label :username
      .input= f.text_field :username, :class => "medium"
    .clearfix
      = f.label :name
      .input= f.text_field :name, :class => "xlarge"
    .clearfix
      = f.label :email
      .input= f.text_field :email, :class => "xlarge"
    .clearfix
      = f.label :password
      .input= f.text_field :password, :class => "medium"
    .clearfix
      = f.label :pass_confirmation
      .input= f.text_field :password_confirmation, :class => "medium"
    .actions
      = f.submit :class => 'btn primary'
      = link_to 'Cancel', admin_users_path, :class => 'btn'

app/views/admin/users/edit.html.haml
= render 'form'

app/views/admin/users/index.html.haml
%h1= @title
%table
  %thead
    %tr
      %th Username
      %th Name
      %th Email
      %th Last post
      %th Last login
      %th Actions
  %tbody
    - for user in @users
      %tr
        %td= user.username
        %td= user.name
        %td= user.email
        %td= link_to user.last_post.title, user.last_post, :target => "_blank"
        %td= l user.last_sign_in_at, :format => :short
        %td
          = link_to "Edit", edit_admin_user_path(user)
          |
          = link_to "Delete", admin_user_path(user), :confirm => 'Are you sure?', :method => :delete, :title => "Delete user"
= link_to "New user", new_admin_user_url, :class => "btn primary"

app/views/admin/users/new.html.haml
= render 'form'

app/views/contact/_error.js.haml
$('#load').fadeOut().empty();
$('#note-error, #note-ok').empty();
$('#note-error').append("<div class='alert-message error'><p><strong>Oh snap!</strong> There was a problem sending your message!</p></div>").fadeIn();
$('#new_contact').fadeIn();

app/views/contact/_success.js.haml
$('#load').fadeOut().empty();
$('#note-error, #note-ok').empty();
$('#note-ok').empty().append("<div class='alert-message success'><p><strong>Awesome!</strong> Message sent successfully!</p></div>").fadeIn();

app/views/contact/contact.html.haml
Hello,
%br/
This email was sent from the contact form on shamanime.com.
%br/
%br/
%strong Name: 
= @params[:name]
%br/
%strong Email:
= @params[:email]
%br/
%strong Message:
%br/
= @params[:message]

app/views/layouts/_disqus_comment_count.html.haml
:javascript
  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function () {
      var s = document.createElement('script'); s.async = true;
      s.type = 'text/javascript';
      s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
      (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
  }());

app/views/layouts/_footer_bottom.html.haml
#footer-bottom
  .container
    %ul#menu-pages.bottom-nav
      = render :partial => 'layouts/primary_nav_itens'
    %p#copyright= t 'footer.copyright'

app/views/layouts/_google_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'YOUR GA CODE HERE']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
      

app/views/layouts/_head.html.haml
%head
  %title= title
  %meta{:charset => t('head.charset')}/
  %meta{:content => t('head.description'), :name => "description"}/
  %meta{:content => t('head.keywords'), :name => "keywords"}/
  = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Goudy+Bookletter+1911"
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags

app/views/layouts/_primary_nav_itens.html.haml
%li= link_to t('navigation.home'), root_path
%li= link_to t('navigation.contact'), contact_path

app/views/layouts/_top_bar.html.haml
.topbar
  .fill
    .container
      %h3= link_to 'shamanime', root_path
      %ul
        = render :partial => 'layouts/primary_nav_itens'
      - if user_signed_in?
        %ul.nav.secondary-nav
          %li.menu
            = link_to "Admin", "#", :class => "menu"
            %ul.menu-dropdown
              %li= link_to t('navigation.admin.manage_posts'), admin_posts_path
              %li= link_to t('navigation.admin.manage_users'), admin_users_path
              %li.divider
              %li= link_to t('navigation.admin.logout'), destroy_user_session_url, :method => :delete

app/views/layouts/admin.html.haml
!!!
%html
  = render :partial => 'layouts/head'
  %body
    = render :partial => 'layouts/top_bar'
    #top
      #top-center
        .container
          #site-name
            %h1.site-title= t 'blog.name'
            %p.description= t 'blog.title'
    #main-area
      #main-top-shadow
        .container
          #content-area
            #content-top
              .row
                .span16.columns
                  - if flash
                    - flash.each do |name, msg| 
                      .alert-message{:class => name}
                        = link_to "×", "#", :class => "close"
                        %p
                          %strong Hey!
                          = msg
                  = yield
    = render :partial => 'layouts/footer_bottom'
    = yield :viewjs

app/views/layouts/application.html.haml
!!!
%html
  = render :partial => 'layouts/head'
  %body
    :javascript
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'shamanime'; // required: replace example with your forum shortname
      var disqus_developer = 1; // uncomment this in development
    
    = yield :headjs
    = render :partial => 'layouts/top_bar'
    #top
      #top-center
        .container
          #site-name
            %h1.site-title= t 'blog.name'
            %p.description= t 'blog.title'
    #main-area
      #main-top-shadow
        .container
          #content-area.area-with-divider
            #content-top.top-with-divider
              .row
                .span11.columns
                  - if flash
                    .alert-home
                      - flash.each do |name, msg| 
                        .alert-message{:class => name}
                          = link_to "×", "#", :class => "close"
                          %p
                            %strong Hey!
                            = msg
                  = yield
                .span5.columns
                  .widget
                    %h4.widgettitle= t 'sidebar.title.recent_posts'
                    - for post in @recent_posts
                      %ul
                        %li
                          = link_to post.title, post_path(post)
                          %span.sidebar-comment-count= link_to 'Comments', post_path(post, :anchor => 'disqus_thread'), :"data-disqus-identifier" => post.id
                  .widget
                    #recentcomments.dsq-widget
                      %h2.dsq-widget-title= t 'sidebar.title.recent_comments'
                      %script{:src => "http://shamanime.disqus.com/recent_comments_widget.js?num_items=5&hide_avatars=0&avatar_size=32&excerpt_length=200", :type => "text/javascript"}
    #footer
      #footer-content
        #footer-top
          .container
            .row
              .span6.columns.footer-widget
                %h4.footertitle= t('footer.boxes.first.title')
                .thumb
                  = image_tag "profile_min.png", :title => "Jefferson Queiroz Venerando", :class => "item-image"
                  %span.overlay
                %p= raw t('footer.boxes.first.content')
              .span5.columns.footer-widget
                %h4.footertitle= t('footer.boxes.second.title')
                %p= t('footer.boxes.second.content')
                %ul
                  %li= link_to "NoSQL e MongoDB", "http://www.slideshare.net/shamanime/nosql-e-mongodb", :target => "_blank"
                  %li= link_to "Rest pra minha namorada", "http://www.slideshare.net/shamanime/rest-pra-minha-namorada", :target => "_blank"
              .span5.columns.footer-widget
                %h4.footertitle= t('footer.boxes.third.title')
                %p= t('footer.boxes.third.content')
                %ul.social-contact
                  %li.skype shamanime
                  %li.twitter= link_to "@shamanime", "http://www.twitter.com/shamanime", :target => "_blank"
                  %li.facebook= link_to "shamanime", "http://www.facebook.com/shamanime", :target => "_blank"
                  %li.slideshare= link_to "shamanime", "http://www.slideshare.net/shamanime", :target => "_blank"
                  %li.orkut= link_to "./jefferson \"shaman\" queiroz", "http://www.orkut.com.br/Main#Profile?uid=2029458311589917449", :target => "_blank"

    = render :partial => 'layouts/footer_bottom'
    = render :partial => 'layouts/google_analytics'
    = render :partial => 'layouts/disqus_comment_count'
    = yield :viewjs

app/views/pages/contact.html.haml
- content_for :viewjs do
  :javascript
    $(document).ready(function() {
      var validator = $("#new_contact").validate({
        errorClass: "help-inline",
        errorElement: "span",
        rules: {
          "contact[name]":  {
                              required: true,
                              minlength: 4
                            },
          "contact[email]": {
                              required: true,
                              email: true
                            },
          "contact[message]": {
                                required: true,
                                minlength: 20
                              }
        },
        highlight: function(element, errorClass, validClass) {
           $(element).addClass(errorClass).removeClass(validClass);
           $(element).parents('div.clearfix:first').addClass('error');
        },
        unhighlight: function(element, errorClass, validClass) {
           $(element).removeClass(errorClass).addClass(validClass);
           $(element).parents('div.clearfix:first').removeClass('error');
        },
        submitHandler: function(form) {
          $('#note-error, #note-ok').empty();
          $('#new_contact').fadeOut();
          $('#load').append("<img src='#{asset_path 'ajax-loader.gif'}' alt='Loading...' id='loading'>").fadeIn();
          $(form).ajaxSubmit();
        }
      });
    });
  
.page.left
  %h1.title= t 'pages.contact.title'
  #note-ok{:style => "display:none"}
  #note-error{:style => "display:none"}
  #contact-form
    = form_for @contact, :url => { :controller => :contact, :action => :contact }, :remote => true, :html => { :class => "form-stacked" } do |f|
      .clearfix
        = f.label :name
        .input= f.text_field :name, :class => "xlarge"
      .clearfix
        = f.label :email
        .input= f.text_field :email, :class => "xlarge"
      .clearfix
        = f.label :message
        .input
          = f.text_area :message, :rows => 6, :class => "xlarge"
          %span.help-block Note: All fields are required.
      .actions= f.submit t('pages.contact.send_button'), :id => 'submit-button', :name => 'submit', :class => "btn primary"
  #load

app/views/posts/index.html.haml
- if @posts.count > 0
  - for post in @posts
    .post
      %h2.title
        = link_to post.title, post
        %small= link_to 'Comments', post_path(post, :anchor => 'disqus_thread'), :"data-disqus-identifier" => post.id
      %p.meta-info= t('post.meta_info', :author => post.user.username, :date => l(post.created_at, :format => :long))
      %p= raw (truncate(post.markdown_body, :length => 600, :separator => ' '))
      %a{:href => post_url(post), :class => 'readmore'}
        %span= t('post.read_more')
- else
  .post
    %p= t ('post.no_posts')
.row
  = paginate @posts

app/views/posts/show.html.haml
- content_for :headjs do
  :javascript
    var disqus_identifier = '#{@post.id}';
  
.post
  %h1.title= link_to @post.title, @post
  %p= raw @post.markdown_body
  %p.meta-info= t('post.meta_info', :author => @post.user.username, :date => l(@post.created_at, :format => :long))
#comment-wrap
  #disqus_thread
  :javascript
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  
  %noscript
    Please enable JavaScript to view the
    %a{:href => "http://disqus.com/?ref_noscript"} comments powered by Disqus.
  %a.dsq-brlink{:href => "http://disqus.com"}
    blog comments powered by
    %span.logo-disqus Disqus